### ISSUE TITLE
npm error log

### ISSUE THREAD

**Issue by Raito92** [cmdcolin/jbrowse_elasticsearch#10]
Hello! 
It looks as if I managed to install successfully my ElasticSearch, but when trying to run npm that's the error log I get...

```
[root@localhost jbrowse1]# npm start
 
> jbrowse_elasticsearch@1.0.5 start /mnt/d8e73111-db5e-4011-87aa-e4d64fb8c1e9/DATA/html/jbrowse1
> node ./bin/www
 
module.js:478
    throw err;
    ^
 
Error: Cannot find module '/mnt/d8e73111-db5e-4011-87aa-e4d64fb8c1e9/DATA/html/jbrowse1/bin/www'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3
 
npm ERR! Linux 3.10.0-957.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! jbrowse_elasticsearch@1.0.5 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jbrowse_elasticsearch@1.0.5 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jbrowse_elasticsearch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jbrowse_elasticsearch
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jbrowse_elasticsearch
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/d8e73111-db5e-4011-87aa-e4d64fb8c1e9/DATA/html/jbrowse1/npm-debug.log

```

**Comment by Raito92** [comment]
I solved the problem, I was running npm start from a wrong location (not the plugin folder).
